image: registry.gitlab.com/testifysec/spire/builder:v0.0.2
stages:
  - clone
  - deps
  - build
  - verify
variables:
  GIT_STRATEGY: none
clone:
  stage: clone
  script:
    - witness run -s clone -a gitlab -a gcp-iit --spiffe-socket=unix:///run/spire/sockets/agent.sock -r https://log.testifysec.io -o /dev/null -- bash -c \
      "git clone ${CI_REPOSITORY_URL} . && git reset --hard ${CI_COMMIT_SHA}"
    - git rev-parse --verify HEAD > commithash
    - witness -c ./witness/.witness-ci.yaml verify -p ./witness/ci-gate-policy.signed.json -f commithash
  artifacts:
    exclude:
      - commithash
    paths:
      - ./*
deps:
  stage: deps
  dependencies:
    - "clone"
  script: 
    - witness -c ./witness/.witness-ci.yaml run -s deps -- /bin/sh -c "go mod vendor"
  artifacts:
    exclude:
      - .git
    paths:
      - ./*
      - ./vendor/*
build:
  stage: build
  dependencies:
    - "deps"
  script:
    - make build-witness
  artifacts:
    exclude:
      - .git
    paths:
      - ./bin/*
      - ./witness/.witness-ci.yaml
      - ./witness/artifact-policy.signed.json
      - ./witness/testpub.pem
verify:
  dependencies:
    - "build"
  stage: verify
  script:
    - for i in $(ls -1 ./bin/*); do witness -c ./witness/.witness-ci.yaml verify -p ./witness/artifact-policy.signed.json -f $i; done
  artifacts:
    paths:
      - ./bin/*