image: registry.gitlab.com/testifysec/spire/builder:v0.0.1

stages:
  - clone
  - build
  - verify


variables:
  GIT_STRATEGY: none
clone:
  stage: clone
  script:
    - witness run -s clone -a gitlab -a gcp-iit --spiffe-socket=unix:///run/spire/sockets/agent.sock -r https://log.testifysec.io -- bash -c \
      "git clone ${CI_REPOSITORY_URL} . && git reset --hard ${CI_COMMIT_SHA}"
    - git rev-parse --verify HEAD > commithash
    - witness -c .witness-ci.yaml verify -p ./policy/ci-gate-policy.signed.json -f commithash
  artifacts:
    exclude:
      - commithash
    paths:
      - ./*
build:
  dependencies:
    - "deps"
  stage: build
  script:
    - |-
      witness -c .witness-ci.yaml run -s build -- /bin/sh -c \
      "make build-witness-ci"
  artifacts:
    exclude:
      - .git
    paths:
      - ./bin/*
verify:
  stage: verify
  script:
    - for i in $(ls -1 ./bin/*); do witness -c ./witness/.witness-ci.yaml verify -p ./witness/artifact-policy.signed.json -f $i; done