run:
  spiffe-socket: "unix:///run/spire/sockets/agent.sock"
  rekor-server: "https://log.testifysec.io"
  attestations:
    - gitlab
    - gcp-iit
    - git
  outfile: /dev/null
verify:
    publickey: ./witness/testpub.pem
    rekor-server: https://log.testifysec.io

